#!/bin/bash

if [ -n "$1" ]; then
    case $1 in
        AOT)
            attrs="AOT, german"
            ;;
        GRS)
            attrs="GRS, german"
            ;;
        *)
            attrs=""
            ;;
    esac
fi

sha=$(sha1sum "$HOME/Documents/Uni/LaTeX/compile/clatex/templateAll.fmt" | head -c 40)

cwd=$(pwd)
cd "$HOME/Documents/Uni/LaTeX/" || exit
last_commit=$(git rev-parse HEAD)
cd "$cwd" || exit

ln -s "$HOME/Documents/Programs/LaTeX/emily_template/compile/template.fmt" .
ln -s "$HOME/Documents/Programs/LaTeX/emily_template/src/" .

echo "%&clatex/templateAll
\endofdump

%\documentclass[11pt]{article}
%\usepackage{template}
%\useTemplateStatic[all]

%\usepackage{src/template}

%! Generated with commit hash: \"$last_commit\"
%! sha1sum of templateAll.fmt: \"$sha\"

\date{$(date +"%Y -- %m -- X")}
\useTemplate[$attrs]


\begin{document}
\maketitle


\end{document}
" >main.tex
